### ISSUE TITLE
Transparent Signature Background

### ISSUE THREAD

**Issue by zerorail** [imsujan276/easy_signature_pad#1]
Hello,

first, i want to thank u for this great lib.
second, i am trying to create a user signature without a white background 

https://firebasestorage.googleapis.com/v0/b/ekyc-12be3.appspot.com/o/files%2F1506%2Fsignature%2Ffff_signature.png?alt=media&token=74b056b0-3206-46ff-bd60-a1de3ecb125f

this method is what i am using to convert from uint8list to png

  
`
    final tempDir = await getTemporaryDirectory();
    final file = File('${tempDir.path}/signature.png');
    file.writeAsBytesSync(List.from(signatureBytes));
`

**Comment by zerorail** [comment]
can u make it an optional to make it transparent or white

this code is from your source code
`  

  //background
    final paint2 = paint
      ..style = PaintingStyle.fill
      ..color = this.transparent?Colors.transparent:Colors.white;
`

**Comment by imsujan276** [comment]
Thank you for the feature information. I have updated the library with the update [easy_signature_pad 1.0.5](https://pub.dev/packages/easy_signature_pad). 
It includes custom background color and making the canvas and/or the generated image transparent
